/**
 * TypeScript → hive-wasm-v1 via AssemblyScript.
 *
 * Same pipeline and ABI as `ndsr compile` (NDSR's reference implementation):
 * discover `hive.define("name", …)` → sort names (func_id = index) →
 * prelude + user code + generated `__alloc`/`__hive_entry` glue → `asc`
 * (pinned version, stub runtime) → ABI validation → package.
 * For an import-free source the produced module.wasm is byte-identical to
 * `ndsr compile`'s.
 */

import { spawnSync } from 'child_process'
import * as fs from 'fs'
import * as os from 'os'
import * as path from 'path'
import { validateAbi } from './abi'
import { buildManifest, packageHbc, sortFunctions, type Packaged } from './hbc'
import { extractDefinedFunctions, lineOf, maskSource } from './source'
import { VERSION } from './version'

/** Exact AssemblyScript version; must match NDSR's `ASC_VERSION`. */
export const ASC_VERSION = '0.28.20'
const MAX_SOURCE_BYTES = 1024 * 1024

export function asCompilerId(): string {
  return `hivekit-js/${VERSION}+assemblyscript@${ASC_VERSION}`
}

export function asPrelude(): string {
  return fs.readFileSync(path.join(__dirname, '..', 'as', 'prelude.ts'), 'utf8')
}

/** Generated dispatch glue; identical to NDSR's `generate_glue`. `names` must be sorted. */
export function generateGlue(names: string[]): string {
  const list = names.map((n) => `"${n}"`).join(', ')
  return `
// ------------------------- generated by ndsr compile -------------------------
const __hive_names: string[] = [${list}];

export function __alloc(len: usize): usize {
  return heap.alloc(len);
}

export function __hive_entry(func_id: i32, ptr: usize, len: usize): i64 {
  if (func_id < 0 || func_id >= __hive_names.length) return -1;
  const name = __hive_names[func_id];
  if (!__hive_registry.has(name)) return -2;
  const f = __hive_registry.get(name);
  const input = len == 0 ? "" : String.UTF8.decodeUnsafe(ptr, len);
  return __hive_pack(f(input));
}
`
}

export class UnsupportedFeatureError extends Error {
  constructor(public readonly problems: string[]) {
    super(
      'This TypeScript uses features the AssemblyScript target does not support:\n' +
        problems.map((p) => '  - ' + p).join('\n') +
        '\nRewrite these parts, or build with the JavaScript engine target (`--target js`), which runs full TypeScript/JavaScript.',
    )
    this.name = 'UnsupportedFeatureError'
  }
}

const HIVEKIT_IMPORT = /^[ \t]*import\s+(?:type\s+)?(?:\{[^}]*\}|\*\s+as\s+[\w$]+|[\w$]+)\s+from\s+(['"])(?:hivekit|hivekit\/as)\1\s*;?[ \t]*$/gm

/**
 * Remove `import … from 'hivekit'` lines (the API is provided by the prelude;
 * the import only serves editors) and reject constructs AssemblyScript cannot
 * compile, with line numbers.
 */
export function prepareAsSource(source: string, file = 'module.ts'): string {
  const stripped = source.replace(HIVEKIT_IMPORT, (m) => m.replace(/[^\n]/g, ' ').trimEnd())
  const code = maskSource(stripped, { strings: true })
  const problems: string[] = []
  const check = (re: RegExp, msg: string): void => {
    const g = new RegExp(re.source, re.flags.includes('g') ? re.flags : re.flags + 'g')
    let m: RegExpExecArray | null
    const seen = new Set<number>()
    while ((m = g.exec(code)) !== null) {
      const line = lineOf(code, m.index)
      if (!seen.has(line)) problems.push(`${file}:${line}: ${msg}`)
      seen.add(line)
    }
  }
  check(/^[ \t]*import\b[^\n]*/m, "only `import … from 'hivekit'` is supported; npm packages and other files cannot be imported")
  check(/\brequire\s*\(/, 'require() is not available')
  check(/\bimport\s*\(/, 'dynamic import() is not available')
  check(/\basync\b|\bawait\b|\bPromise\b/, 'async/await and Promise are not supported (hive.call is synchronous)')
  check(/:\s*any\b|\bas\s+any\b|<any>/, "the type 'any' is not supported; use a concrete type")
  check(/:\s*unknown\b|\bas\s+unknown\b/, "the type 'unknown' is not supported; use a concrete type")
  check(/\bundefined\b/, "'undefined' is not supported; use null with a nullable type (T | null)")
  check(/\btry\s*\{|\bcatch\s*[({]/, 'try/catch is not supported (exceptions abort the call); use hive.fail() for errors')
  check(/\bJSON\s*\./, 'there is no built-in JSON object; build JSON strings by hand or use the JavaScript target')
  check(/\bMath\s*\.\s*random\b|\bDate\s*\.\s*now\b|\bnew\s+Date\s*\(\s*\)/, 'clocks and randomness are not available (non-deterministic)')
  check(/\bconsole\s*\./, 'console is not available; use hive.log()')
  check(/\beval\s*\(|\bnew\s+Function\s*\(/, 'eval / new Function are not supported')
  check(/\bdelete\s+[\w$]/, "the 'delete' operator is not supported; use a Map")
  check(/\bfunction\s*\*|\byield\b/, 'generators are not supported')
  check(/\bSymbol\s*[.(]/, 'Symbols are not supported')
  for (const reserved of ['__hive_', '__alloc']) {
    if (stripped.includes(reserved)) problems.push(`identifiers containing "${reserved}" are reserved for the HiveKit glue`)
  }
  if (problems.length) throw new UnsupportedFeatureError(problems)
  return stripped
}

/** Full source handed to asc (prelude + user code + glue), as in `ndsr compile`. */
export function assembleAsSource(user: string, names: string[]): string {
  return `${asPrelude()}\n// ------------------------------ user code -------------------------------\n${user}\n${generateGlue(names)}`
}

function ascPath(): string {
  const pkg = require.resolve('assemblyscript/package.json')
  const installed = JSON.parse(fs.readFileSync(pkg, 'utf8')).version
  if (installed !== ASC_VERSION) {
    throw new Error(`assemblyscript ${installed} is installed but HiveKit requires exactly ${ASC_VERSION}`)
  }
  return path.join(path.dirname(pkg), 'bin', 'asc.js')
}

/** Rewrite `module.ts(L,C)` references in asc output to the user's file and line. */
export function mapAscErrors(log: string, userFile: string, userLineOffset: number, userLines: number): string {
  let mapped = log.replace(/module\.ts\((\d+),(\d+)\)/g, (_m, l: string, c: string) => {
    const line = Number(l) - userLineOffset
    if (line >= 1 && line <= userLines) return `${userFile}(${line},${c})`
    return line < 1 ? `<hivekit prelude>(${l},${c})` : `<generated glue>(${l},${c})`
  })
  const hints: string[] = []
  if (/Closures/i.test(log)) hints.push('AssemblyScript functions cannot capture local variables (closures); pass values explicitly or use module-level variables.')
  if (/TS2322|TS2345/.test(log) && /literal/i.test(log)) hints.push('Object literals need an explicit class type in AssemblyScript.')
  if (hints.length) mapped += '\nHints:\n' + hints.map((h) => '  - ' + h).join('\n')
  return mapped
}

export interface CompileAsOptions {
  name: string
  version?: string
  description?: string
  /** Shown in error messages. */
  file?: string
}

/** Compile a HiveKit AssemblyScript (TypeScript-subset) module to a `.hbc`. */
export function compileAssemblyScript(source: string, opts: CompileAsOptions): Packaged & { wasm: Uint8Array } {
  if (Buffer.byteLength(source) > MAX_SOURCE_BYTES) throw new Error('source exceeds 1 MiB')
  const file = opts.file ?? 'module.ts'
  const user = prepareAsSource(source, file)
  const names = sortFunctions(extractDefinedFunctions(user))
  const full = assembleAsSource(user, names)

  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hivec-as-'))
  try {
    const src = path.join(dir, 'module.ts')
    const out = path.join(dir, 'module.wasm')
    fs.writeFileSync(src, full)
    const r = spawnSync(
      process.execPath,
      [ascPath(), src, '--outFile', out, '--runtime', 'stub', '--optimizeLevel', '3', '--shrinkLevel', '0', '--noColors'],
      { cwd: dir, encoding: 'utf8', timeout: 180_000 },
    )
    if (r.error) throw r.error
    if (r.status !== 0) {
      const offset = asPrelude().split('\n').length + 1
      const log = mapAscErrors(`${r.stdout ?? ''}${r.stderr ?? ''}`, file, offset, user.split('\n').length)
      throw new Error(`AssemblyScript compilation failed:\n${log}`)
    }
    const wasm = new Uint8Array(fs.readFileSync(out))
    try {
      validateAbi(wasm)
    } catch (e) {
      throw new Error(`asc output does not satisfy the hive-wasm-v1 ABI: ${(e as Error).message}`)
    }
    const manifest = buildManifest({
      name: opts.name,
      language: 'assemblyscript',
      compiler: asCompilerId(),
      functions: names,
      version: opts.version,
      description: opts.description,
    })
    return { ...packageHbc(manifest, wasm), wasm }
  } finally {
    fs.rmSync(dir, { recursive: true, force: true })
  }
}
