//! Runtime support for the code generated by `#[hive_export]` and `hive_module!`.
//! Not a public API.

use crate::{Export, Module};
use serde::de::DeserializeOwned;

/// Decode the input bytes of a call as JSON. Empty input decodes as `null`.
pub fn decode_input<T: DeserializeOwned>(input: &[u8]) -> Result<T, String> {
    let bytes: &[u8] = if input.is_empty() { b"null" } else { input };
    serde_json::from_slice(bytes).map_err(|e| format!("invalid input: {e}"))
}

const fn str_cmp(a: &str, b: &str) -> i32 {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    let mut i = 0;
    while i < a.len() && i < b.len() {
        if a[i] != b[i] {
            return if a[i] < b[i] { -1 } else { 1 };
        }
        i += 1;
    }
    if a.len() == b.len() {
        0
    } else if a.len() < b.len() {
        -1
    } else {
        1
    }
}

/// Sort exports bytewise by name at compile time; duplicate names fail the build.
pub const fn sort_exports<const N: usize>(mut a: [Export; N]) -> [Export; N] {
    let mut i = 1;
    while i < N {
        let mut j = i;
        while j > 0 && str_cmp(a[j - 1].name, a[j].name) > 0 {
            let t = a[j - 1];
            a[j - 1] = a[j];
            a[j] = t;
            j -= 1;
        }
        i += 1;
    }
    let mut k = 1;
    while k < N {
        if str_cmp(a[k - 1].name, a[k].name) == 0 {
            panic!("hive_module!: two functions are exported under the same name");
        }
        k += 1;
    }
    a
}

/// Length of the `hivekit.functions` section: every name followed by `\n`.
pub const fn names_len(a: &[Export]) -> usize {
    let mut n = 0;
    let mut i = 0;
    while i < a.len() {
        n += a[i].name.len() + 1;
        i += 1;
    }
    n
}

/// Contents of the `hivekit.functions` section.
pub const fn names_bytes<const L: usize>(a: &[Export]) -> [u8; L] {
    let mut out = [0u8; L];
    let mut o = 0;
    let mut i = 0;
    while i < a.len() {
        let b = a[i].name.as_bytes();
        let mut j = 0;
        while j < b.len() {
            out[o] = b[j];
            o += 1;
            j += 1;
        }
        out[o] = b'\n';
        o += 1;
        i += 1;
    }
    out
}

/// `__alloc(len)`: a real linear-memory allocation of `len` bytes (align 1).
/// Buffers handed over by the host are later reclaimed with
/// `Vec::from_raw_parts(ptr, len, len)`, which matches this layout.
pub fn alloc(len: i32) -> i32 {
    let len = len as u32 as usize;
    if len == 0 {
        return 0;
    }
    let layout = match std::alloc::Layout::from_size_align(len, 1) {
        Ok(l) => l,
        Err(_) => return 0,
    };
    // SAFETY: layout has non-zero size.
    let p = unsafe { std::alloc::alloc(layout) };
    p as usize as i32
}

/// Take ownership of a host-written buffer `(ptr, len)` allocated by [`alloc`].
///
/// # Safety
/// `(ptr, len)` must come from the host per the hive-wasm-v1 ABI (an [`alloc`]
/// result of exactly `len` bytes), or be `(_, 0)`.
pub unsafe fn take_buffer(ptr: u32, len: u32) -> Vec<u8> {
    if len == 0 {
        return Vec::new();
    }
    Vec::from_raw_parts(ptr as usize as *mut u8, len as usize, len as usize)
}

/// Leak `out` and return it packed as `(ptr << 32) | len` (`0` = empty).
pub fn pack_output(out: Vec<u8>) -> i64 {
    if out.is_empty() {
        return 0;
    }
    let b = out.into_boxed_slice();
    let len = b.len() as u64;
    let ptr = Box::into_raw(b) as *mut u8 as usize as u64;
    ((ptr << 32) | len) as i64
}

/// Unpack a non-negative packed value into `(ptr, len)`.
pub fn unpack(v: i64) -> (u32, u32) {
    let u = v as u64;
    ((u >> 32) as u32, u as u32)
}

/// `__hive_entry(func_id, ptr, len)`: dispatch by index into the sorted table.
pub fn entry(module: &'static Module, func_id: i32, ptr: i32, len: i32) -> i64 {
    crate::host::install_panic_hook();
    // SAFETY: per the ABI the host passes either (0, 0) or a buffer it obtained from __alloc(len).
    let input = unsafe { take_buffer(ptr as u32, len as u32) };
    let Some(export) = module.export(func_id as u32 as usize) else {
        crate::abort(&format!("unknown func_id {func_id}"));
    };
    match (export.func)(&input) {
        Ok(out) => pack_output(out),
        Err(msg) => crate::abort(&msg),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn f(_: &[u8]) -> Result<Vec<u8>, String> {
        Ok(Vec::new())
    }
    const fn e(name: &'static str) -> Export {
        Export { name, func: f }
    }

    #[test]
    fn sorts_bytewise_at_compile_time() {
        const S: [Export; 4] = sort_exports([e("stats"), e("addNumbers"), e("Zeta"), e("add")]);
        let names: Vec<_> = S.iter().map(|x| x.name).collect();
        assert_eq!(names, ["Zeta", "add", "addNumbers", "stats"]);
        const L: usize = names_len(&S);
        const B: [u8; L] = names_bytes::<L>(&S);
        assert_eq!(&B, b"Zeta\nadd\naddNumbers\nstats\n");
    }

    #[test]
    #[should_panic(expected = "same name")]
    fn duplicate_names_rejected() {
        sort_exports([e("a"), e("b"), e("a")]);
    }

    #[test]
    fn pack_roundtrip() {
        assert_eq!(pack_output(Vec::new()), 0);
        assert_eq!(unpack(((0x1234u64 << 32) | 7) as i64), (0x1234, 7));
    }

    #[test]
    fn decode() {
        assert_eq!(
            decode_input::<serde_json::Value>(b"").unwrap(),
            serde_json::Value::Null
        );
        assert_eq!(decode_input::<i64>(b"42").unwrap(), 42);
        assert!(decode_input::<i64>(b"{")
            .unwrap_err()
            .starts_with("invalid input"));
    }
}
