//! HiveKit Rust SDK: write modules for the Necter network's NDSR runtime.
//!
//! A module is a `cdylib` compiled for `wasm32-unknown-unknown` that speaks the
//! `hive-wasm-v1` guest ABI (NDSR `docs/HBC_SPEC.md`). This crate provides the
//! ABI glue (via [`hive_module!`]), typed access to the host (storage, events,
//! cross-module calls, hashing, logging, abort) and an in-process mock host so
//! the same code can be unit tested natively with `cargo test`.
//!
//! ```rust
//! use hivekit::prelude::*;
//!
//! #[hive_export]
//! fn add_numbers(input: Value) -> Value {
//!     let a = input["a"].as_i64().unwrap_or(0);
//!     let b = input["b"].as_i64().unwrap_or(0);
//!     json!({ "total": a + b })
//! }
//!
//! #[hive_export("increment")]
//! fn bump(input: Value) -> Result<Value, String> {
//!     let by = input["by"].as_i64().ok_or("`by` is required")?;
//!     let n = storage::get_json::<i64>("counter").unwrap_or(0) + by;
//!     storage::set_json("counter", &n);
//!     emit("incremented", &json!({ "value": n }));
//!     Ok(json!({ "value": n }))
//! }
//!
//! hive_module!(add_numbers, bump);
//!
//! # fn main() {
//! // Native test: the export table is sorted, func_id = index.
//! assert_eq!(HIVE_MODULE.functions(), vec!["addNumbers", "increment"]);
//! assert_eq!(HIVE_MODULE.invoke("addNumbers", json!({"a": 2, "b": 40})).unwrap()["total"], 42);
//! assert_eq!(HIVE_MODULE.invoke("increment", json!({"by": 5})).unwrap()["value"], 5);
//! assert!(HIVE_MODULE.invoke("increment", json!({})).is_err());
//! # }
//! ```
//!
//! Build and package with the `hivec` CLI from this crate:
//!
//! ```text
//! hivec build                # cargo build --target wasm32-unknown-unknown --release + package
//! hivec inspect dist/my_module.hbc
//! hivec run dist/my_module.hbc addNumbers '{"a":1,"b":2}'
//! ```

#![cfg_attr(docsrs, feature(doc_cfg))]

pub use hivekit_macro::{hive_export, hive_module};
pub use serde_json::{json, Value};

#[doc(hidden)]
pub mod __rt;
mod host;

pub use host::{abort, call, call_json, emit, hash, log, storage, CallError};

#[cfg(not(target_arch = "wasm32"))]
pub use host::testing;

use serde::Serialize;

/// One exported function: its export name and the type-erased wrapper
/// generated by `#[hive_export]` (input bytes -> output bytes or error).
#[derive(Clone, Copy)]
pub struct Export {
    pub name: &'static str,
    pub func: fn(&[u8]) -> Result<Vec<u8>, String>,
}

impl std::fmt::Debug for Export {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Export").field("name", &self.name).finish()
    }
}

/// A module's export table, sorted bytewise by name (index = `func_id`).
/// Generated by [`hive_module!`] as `HIVE_MODULE`.
#[derive(Debug)]
pub struct Module {
    exports: &'static [Export],
}

impl Module {
    #[doc(hidden)]
    pub const fn new(exports: &'static [Export]) -> Self {
        Module { exports }
    }

    /// Export names in `func_id` order (the manifest `functions` list).
    pub fn functions(&self) -> Vec<&'static str> {
        self.exports.iter().map(|e| e.name).collect()
    }

    /// `func_id` of an export.
    pub fn func_id(&self, name: &str) -> Option<usize> {
        self.exports
            .binary_search_by(|e| e.name.as_bytes().cmp(name.as_bytes()))
            .ok()
    }

    /// The export with this `func_id`.
    pub fn export(&self, func_id: usize) -> Option<&Export> {
        self.exports.get(func_id)
    }

    /// Run a function on raw input bytes, natively, against the mock host
    /// ([`testing`]). Like NDSR, a failed call (error return, [`abort`] or
    /// panic) leaves storage and events untouched.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn invoke_raw(&'static self, name: &str, input: &[u8]) -> Result<Vec<u8>, String> {
        host::testing::invoke_top(self, name, input)
    }

    /// [`Module::invoke_raw`] with JSON in and out. Non-JSON output is
    /// returned as a JSON string.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn invoke(&'static self, name: &str, input: Value) -> Result<Value, String> {
        let bytes = if input.is_null() {
            Vec::new()
        } else {
            serde_json::to_vec(&input).map_err(|e| e.to_string())?
        };
        let out = self.invoke_raw(name, &bytes)?;
        Ok(serde_json::from_slice(&out)
            .unwrap_or_else(|_| Value::String(String::from_utf8_lossy(&out).into_owned())))
    }
}

/// Wrap any `Serialize` value to return it as JSON from a `#[hive_export]` fn.
#[derive(Debug, Clone)]
pub struct Json<T>(pub T);

/// Conversion of a `#[hive_export]` return value into output bytes.
///
/// * `Value`, `Json<T>`: JSON text
/// * `String`, `&'static str`: the text as-is (not JSON-quoted)
/// * `()`: empty output
/// * `Result<R, E: Display>`: `Ok` as above, `Err` aborts the call with the message
pub trait HiveOutput {
    fn into_output(self) -> Result<Vec<u8>, String>;
}

impl HiveOutput for Value {
    fn into_output(self) -> Result<Vec<u8>, String> {
        serde_json::to_vec(&self).map_err(|e| e.to_string())
    }
}

impl<T: Serialize> HiveOutput for Json<T> {
    fn into_output(self) -> Result<Vec<u8>, String> {
        serde_json::to_vec(&self.0).map_err(|e| e.to_string())
    }
}

impl HiveOutput for String {
    fn into_output(self) -> Result<Vec<u8>, String> {
        Ok(self.into_bytes())
    }
}

impl HiveOutput for &'static str {
    fn into_output(self) -> Result<Vec<u8>, String> {
        Ok(self.as_bytes().to_vec())
    }
}

impl HiveOutput for () {
    fn into_output(self) -> Result<Vec<u8>, String> {
        Ok(Vec::new())
    }
}

impl<R: HiveOutput, E: std::fmt::Display> HiveOutput for Result<R, E> {
    fn into_output(self) -> Result<Vec<u8>, String> {
        match self {
            Ok(r) => r.into_output(),
            Err(e) => Err(e.to_string()),
        }
    }
}

/// Everything a module needs: `use hivekit::prelude::*;`
pub mod prelude {
    pub use crate::{
        abort, call, call_json, emit, hash, hive_export, hive_module, json, log, storage,
        CallError, HiveOutput, Json, Value,
    };
}
